title: "EvPres"

pagetitle: "EvPres"

lang_name: EN

author:
  bio: >-
    **Evaluation of prestressing forces in prestressed concrete bridges** 
    <br>    
    <br>    
    <img src="/images/evpres_logo_biele.png"/>
    <br>
      This project has been supported by the Slovak Research and Development Agency under the contract No. **APVV-23-0196**
    <br> 
  links:
    - label: "TUKE"
      url: "https://www.tuke.sk/"
    - label: "APVV"
      url: "https://www.apvv.sk/"    
    - label: "LinkedIN"
      url: "https://www.linkedin.com/company/evpres/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/EvPres/"


footer:
  links:
    - label: "TUKE"
      url: "https://www.tuke.sk/"
    - label: "APVV"
      url: "https://www.apvv.sk/"    
    - label: "LinkedIN"
      url: "https://www.linkedin.com/company/evpres/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/EvPres/"

